name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: docker-cuda-test
  DOCKER_USERNAME: flowlab

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: version
      run: |
        VERSION="dev"
        if [[ "${GITHUB_REF/refs\/tags\//}" != "refs/heads/"* ]] ; then
          VERSION="${GITHUB_REF/refs\/tags\//}"
        fi
        echo ::set-output name=VERSION::${VERSION}
    - name: Build the Docker image
      run: |
        VERSION=${{ steps.version.outputs.VERSION }}
        DOCKER_VER=${VERSION#"v"}
        docker build . --file Dockerfile --tag ${DOCKER_USERNAME}/${IMAGE}:${DOCKER_VER}

    - name: Setup DockerHub
      run: |
        docker login --username flowlab --password ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish DockerHub
      run: |
        docker push --all-tags ${DOCKER_USERNAME}/${IMAGE}
